### PR TITLE
Improve annotation system

### PR DESCRIPTION
**Pull request by Nuckerr**
Sorry if making another pr is the wrong way to go about this.

Anyways, this just moves the `annotateClass` method into the `FlatFile` class so it is inherited by all other config classes. It also resolves a few comments made on the previous pr

### CODE REVIEW

**Comment by KotlinFactory** [comment]
Hey,
this PR looks great I will have a look at this.

Maybe @yoyosource is already doing a review they were pretty helpful previous times.

Regards,
Leonhard

**Comment by KotlinFactory** [comment]
Merged, thanks

**Comment by yoyosource** [comment]
No I did not review this. As I got the mail too late.

**Comment by yoyosource** [comment]
But I like that you changed it @Nuckerr and have nothing to complain about.

**Pull request merged**
